FROM nvcr.io/nvidia/l4t-ml:r32.5.0-py3
MAINTAINER 'ivanhahanov@gmail.com'

WORKDIR face_id


COPY requirements.txt.jetson .
RUN pip3 install -r requirements.txt.jetson

COPY . .

ENV LD_LIBRARY_PATH=/usr/lib/aarch64-linux-gnu/tegra
ENV CONFIG='Default'
ENV LIVENESS_DETECTOR_PATH='model/liveness_detector.ckpt'
ENV KNOWN_FACES_DIR='/known_faces'
ENV UPLOAD_DIR='/uploads'

CMD [ "gunicorn", "app:app", "--timeout=120", "-b=0.0.0.0:80", "--log-level=DEBUG"]